// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3IWC8niFgEKv6XlWX7Rb54toepMYmHV4',
    appId: '1:741763798026:web:a5c4182ebc0a4ae2e1bbf3',
    messagingSenderId: '741763798026',
    projectId: 'hungrx-4ff6b',
    authDomain: 'hungrx-4ff6b.firebaseapp.com',
    storageBucket: 'hungrx-4ff6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYO5FL_R6nOBlL9QJXx_1Gb34hrykswXQ',
    appId: '1:741763798026:android:d4eddc5047fe97b6e1bbf3',
    messagingSenderId: '741763798026',
    projectId: 'hungrx-4ff6b',
    storageBucket: 'hungrx-4ff6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczcBgvnZhgDH6hSpV3J9bAE8B5fo7FtA',
    appId: '1:741763798026:ios:3e11cf1a9e622ea6e1bbf3',
    messagingSenderId: '741763798026',
    projectId: 'hungrx-4ff6b',
    storageBucket: 'hungrx-4ff6b.appspot.com',
    iosBundleId: 'com.example.calculatorApp',
  );
}
